namespace java ele.me.hackathon.tank.player

struct Position {
    1:i32 x,
    2:i32 y
}

enum Direction {
    UP = 1,
    DOWN = 2,
    LEFT = 3,
    RIGHT = 4
}

struct Tank {
    1:i32 id,
    2:Position pos,
    3:Direction dir,
    4:i32 hp
}

struct Shell {
    1:i32 id,
    2:Position pos,
    3:Direction dir,
}

struct GameState {
    1:list<Tank> tanks,
    2:list<Shell> shells,
    3:i32 yourFlags,
    4:i32 enemyFlags
}

struct Order {
    1:i32 tankId,
    2:string order,
    3:Direction dir
}

service PlayerServer {
    void uploadMap(1:list<list<i32>> gamemap);
    void assignTanks(1:list<i32> tanks);
    void latestState(1:GameState state);
    list<Order> getNewOrders();
}